version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-supermercado
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - supermercado-net

  app-vendas:
    build: ./app-vendas
    depends_on:
      - mysql
    networks:
      - supermercado-net

  nginx:
    build: ./nginx
    ports:
      - "4500:80"
    depends_on:
      - app-vendas
    networks:
      - supermercado-net

volumes:
  mysql_data:

networks:
  supermercado-net:
